"""User-configurable Microsoft Teams alerts on raw press_data tags.

Lets someone build a rule set (e.g. "Billet Temperature Actual (F) < 700
AND Extrusion Active is False, for >= 60s") entirely from the live
press_data document's own fields. The ONLY press-specific piece in this
whole module is list_available_tags() (and the frontend's PRESET_TRIGGERS
shortcuts) - the trigger/condition schema, comparator set, compound-AND
evaluation, and one-time/recurring mechanics below are all written in
terms of generic "field: value" pairs, not press-specific behavior, so
this same engine works for any document shape someone points
list_available_tags() at.

Each rule posts to a Teams "Incoming Webhook" (or a Workflows app
"Post to a channel when a webhook request is received" flow) URL
supplied when the alert is created - pasted in by whoever owns that
Teams channel, not generated by this app. That URL is a bearer secret
(anyone who has it can post into that channel), and this whole app has
no authentication on any endpoint, so it is written to Mongo but never
read back out through the API in full - see app.py's _serialize_rule,
which only ever returns a masked version of it.

An earlier version of this used ntfy.sh (a public topic + QR code to
scan into its app) instead of Teams. That was dropped: getting a phone
to reliably deep-link into a specific app from a scanned link depends on
OS-level Universal/App Links being honored by however it's scanned -
confirmed unreliable on iOS - which no provider choice fixes. A Teams
webhook needs no subscription action from the recipient at all; they
just need to already be in the channel.

Runs as its own background poller, independent of billet_monitor.py's
Detector - same press_data document, same 2s cadence, but deliberately
NOT sharing that loop. A slow/unreachable webhook endpoint must never
delay the billet-cycle/state_events tracking that loop is responsible
for (and per that module's own POLL_DISABLED lesson, this one is
skipped for a local dev instance the same way - see app.py).

Trigger schema - one trigger is a compound (AND-only; multiple
independent triggers on one rule already give OR from the user's
perspective, since any one of them firing sends a message) list of
conditions that must ALL hold, continuously, for sustained_s before it
fires:
    {
        "id": "<hex>",
        "conditions": [
            {"field": str, "type": "bool", "equals": bool, "mode": "becomes"|"stays"},
            {"field": str, "type": "numeric", "comparator": "<"|"<="|">"|">="|"=="|"!=", "threshold": number},
            ...
        ],
        "sustained_s": number,
        "active": bool,
    }
"mode" on a bool condition is display-only ("becomes True" vs "stays
True" read differently but evaluate identically - see describe_condition)
- purely so the wording someone picked while building it survives into
what's actually shown later, without a second code path.

A rule (one webhook, its label/repeat setting, and its triggers) also
carries "repeat": "recurring" (default - stays armed, re-fires each time
a trigger re-trips after clearing) or "one_time" (deleted entirely the
first time any of its triggers fires, per-request).
"""
import json
import operator as _op
import re
import secrets
import threading
import time
import urllib.error
import urllib.request

from billet_monitor import FLD_DATETIME, POLL_INTERVAL_S, plant_now
from db import get_db

REPEAT_MODES = ("recurring", "one_time")

_COMPARATORS = {
    "<": _op.lt,
    "<=": _op.le,
    ">": _op.gt,
    ">=": _op.ge,
    "==": _op.eq,
    "!=": _op.ne,
}

# Symbols alone assume everyone reads math notation fluently - spelling
# each one out alongside it (see describe_condition) means they don't
# have to.
COMPARATOR_PHRASES = {
    "<": "less than",
    "<=": "less than or equal to",
    ">": "greater than",
    ">=": "greater than or equal to",
    "==": "equal to",
    "!=": "not equal to",
}

BOOL_MODES = ("becomes", "stays")


def comparator_options():
    """[{"value": "<", "label": "less than"}, ...] in a sensible display
    order - for the frontend's condition dropdown, so the symbol/phrase
    pairing is defined once, here, rather than duplicated client-side."""
    return [{"value": symbol, "label": phrase} for symbol, phrase in COMPARATOR_PHRASES.items()]


def bool_mode_options():
    return [
        {"value": "becomes", "label": "becomes"},
        {"value": "stays", "label": "stays"},
    ]


def mask_webhook_url(url):
    """Never return the real secret through the API - just enough of
    the tail to let someone recognize which channel a given alert
    already points to, without exposing something that could be pasted
    elsewhere to post into a real Teams channel."""
    if not url:
        return None
    tail = url[-6:] if len(url) > 6 else url
    return f"...{tail}"


def list_available_tags(db):
    """Every press_data field that's a plain bool or number, since those
    are the only two kinds of condition the trigger builder understands.
    Read from the latest live document rather than a hardcoded field
    list, so it stays correct if GetSendPressDataToDB.py's own tag list
    ever changes - the same reason billet_monitor.py polls press_data
    instead of the PLC directly. This is the one press-specific function
    in this module - see the module docstring."""
    doc = db.press_data.find_one({}, sort=[(FLD_DATETIME, -1)])
    if not doc:
        return []
    tags = []
    for key, value in doc.items():
        if key == "_id":
            continue
        if isinstance(value, bool):
            tags.append({"field": key, "type": "bool"})
        elif isinstance(value, (int, float)):
            tags.append({"field": key, "type": "numeric"})
    tags.sort(key=lambda t: t["field"])
    return tags


def _pretty_field(field):
    # "Billet Temperature Actual (F)" -> "Billet Temperature Actual" -
    # the unit/type suffix is useful in a dropdown but redundant (and a
    # little odd-reading, e.g. "(Bool)") once it's part of a sentence.
    return re.sub(r"\s*\([^)]*\)\s*$", "", field).strip()


def _format_duration(seconds):
    seconds = int(seconds)
    if seconds < 60:
        return f"{seconds}s"
    minutes, sec = divmod(seconds, 60)
    return f"{minutes}m{sec}s" if sec else f"{minutes}m"


def describe_condition(condition):
    pretty = _pretty_field(condition["field"])
    if condition["type"] == "bool":
        word = "stays" if condition.get("mode") == "stays" else "becomes"
        return f"{pretty} {word} {'True' if condition.get('equals', True) else 'False'}"
    comparator = condition.get("comparator")
    phrase = COMPARATOR_PHRASES.get(comparator, comparator)
    return f"{pretty} {comparator} {condition.get('threshold')} ({phrase})"


def describe_trigger(trigger):
    core = " AND ".join(describe_condition(c) for c in trigger.get("conditions", []))
    sustained_s = trigger.get("sustained_s") or 0
    if sustained_s > 0:
        # Plain ASCII, not "≥" - Windows' default console codepage
        # (cp1252) can't encode that and print() crashes on it, and this
        # string also goes out verbatim in the Teams message itself.
        core += f" for >={_format_duration(sustained_s)}"
    return core


def validate_condition(condition):
    if not isinstance(condition, dict):
        return "each condition must be an object"
    field = condition.get("field")
    if not field or not isinstance(field, str):
        return "each condition needs a field"
    ctype = condition.get("type")
    if ctype not in ("bool", "numeric"):
        return "type must be 'bool' or 'numeric'"
    if ctype == "bool":
        if not isinstance(condition.get("equals"), bool):
            return "a bool condition needs equals: true/false"
        if condition.get("mode") is not None and condition.get("mode") not in BOOL_MODES:
            return f"mode must be one of {BOOL_MODES}"
    else:
        if condition.get("comparator") not in _COMPARATORS:
            return f"comparator must be one of {sorted(_COMPARATORS)}"
        threshold = condition.get("threshold")
        if isinstance(threshold, bool) or not isinstance(threshold, (int, float)):
            return "a numeric condition needs a numeric threshold"
    return None


def validate_trigger(trigger):
    if not isinstance(trigger, dict):
        return "each trigger must be an object"
    conditions = trigger.get("conditions")
    if not isinstance(conditions, list) or not conditions:
        return "each trigger needs at least one condition"
    for condition in conditions:
        err = validate_condition(condition)
        if err:
            return err
    sustained_s = trigger.get("sustained_s", 0)
    if isinstance(sustained_s, bool) or not isinstance(sustained_s, (int, float)) or sustained_s < 0:
        return "sustained_s must be a non-negative number"
    return None


def _build_condition(c):
    condition = {"field": c["field"], "type": c["type"]}
    if c["type"] == "bool":
        condition["equals"] = c["equals"]
        condition["mode"] = c.get("mode") if c.get("mode") in BOOL_MODES else "becomes"
    else:
        condition["comparator"] = c["comparator"]
        condition["threshold"] = c["threshold"]
    return condition


def validate_webhook_url(url):
    if not url or not isinstance(url, str):
        return "a Teams webhook URL is required"
    if not url.startswith("https://"):
        return "the webhook URL must start with https://"
    return None


def validate_recipient_email(email):
    """Optional - only checked at all if someone actually provided a
    value. Deliberately loose (just "looks like an email"): a strict
    regex mostly just rejects valid-but-unusual addresses, and the real
    validation that matters happens on Teams/Power Automate's side when
    it tries to resolve the address to a person."""
    if email is None or email == "":
        return None
    if not isinstance(email, str) or email.count("@") != 1:
        return "recipient_email doesn't look like a valid email address"
    local, _, domain = email.partition("@")
    if not local or "." not in domain:
        return "recipient_email doesn't look like a valid email address"
    return None


def build_rule_doc(payload):
    """Validates payload (the POST /api/alerts body) and returns
    (doc, None) or (None, error_message)."""
    if not isinstance(payload, dict):
        return None, "invalid request body"

    webhook_url = payload.get("webhook_url")
    err = validate_webhook_url(webhook_url)
    if err:
        return None, err

    recipient_email = payload.get("recipient_email") or None
    err = validate_recipient_email(recipient_email)
    if err:
        return None, err

    triggers_in = payload.get("triggers")
    if not isinstance(triggers_in, list) or not triggers_in:
        return None, "at least one trigger is required"

    triggers = []
    for t in triggers_in:
        err = validate_trigger(t)
        if err:
            return None, err
        triggers.append({
            "id": secrets.token_hex(4),
            "conditions": [_build_condition(c) for c in t["conditions"]],
            "sustained_s": t.get("sustained_s", 0),
            "active": True,
        })

    label = payload.get("label")
    if label is not None and not isinstance(label, str):
        return None, "label must be a string"

    repeat = payload.get("repeat", "recurring")
    if repeat not in REPEAT_MODES:
        return None, f"repeat must be one of {REPEAT_MODES}"

    return {
        "label": (label.strip() or None) if label else None,
        "active": True,
        "repeat": repeat,
        "created_at": plant_now().isoformat(),
        "webhook_url": webhook_url,
        "recipient_email": recipient_email,
        "triggers": triggers,
    }, None


def send_teams(webhook_url, title, message, recipient_email=None, timeout=10):
    """Adaptive Card payload, wrapped in the "attachments" array a
    Workflows-app "Post an Adaptive Card" flow expects to loop over -
    confirmed live against a real webhook: a classic MessageCard payload
    (understood by the now-being-retired O365 Connector Incoming
    Webhook) makes that kind of flow fail immediately, since its
    for-each over attachments finds nothing to iterate.

    One TextBlock per line rather than a single block with embedded
    "\\n"s - Adaptive Cards treat a literal newline inside one
    TextBlock's text as a space, not a line break.

    recipient_email is a top-level sibling of "attachments", not part
    of the card itself - lets ONE shared flow (its "Post card in a chat
    or channel" action's Recipient field bound to
    triggerBody()?['recipient_email']) serve every alert anyone creates,
    routed per-request to whoever it's for, instead of needing a
    separate flow built per person."""
    body = [{"type": "TextBlock", "text": title, "weight": "Bolder", "size": "Medium", "wrap": True}]
    body.extend({"type": "TextBlock", "text": line, "wrap": True} for line in message.split("\n") if line)
    payload = {
        "attachments": [
            {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "type": "AdaptiveCard",
                    "version": "1.4",
                    "body": body,
                },
            }
        ]
    }
    if recipient_email:
        payload["recipient_email"] = recipient_email
    req = urllib.request.Request(
        webhook_url,
        data=json.dumps(payload).encode("utf-8"),
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return True, resp.status, resp.read().decode("utf-8", "replace")
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", "replace")
        return False, exc.code, body
    except (urllib.error.URLError, OSError) as exc:
        return False, None, str(exc)


def _send_teams_async(webhook_url, title, message, recipient_email=None):
    # Fire-and-forget on its own thread - see module docstring on why
    # this loop must never block on the webhook endpoint's response time.
    def _run():
        ok, status, body = send_teams(webhook_url, title, message, recipient_email=recipient_email)
        if not ok:
            print(f"[alerts] Teams send failed ({status}): {body[:200]}")

    threading.Thread(target=_run, daemon=True).start()


class AlertEvaluator:
    """Edge-triggered: a trigger fires once when ALL of its conditions
    have been continuously true together for >= sustained_s, then stays
    quiet (no repeat messages while they keep holding) until they clear
    and trip again - nobody wants a message every 2 seconds for as long
    as, say, Manual mode stays active. A "one_time" rule is deleted
    outright the moment any one of its triggers fires this way, instead
    of just re-arming."""

    def __init__(self, db):
        self._db = db
        # (rule_id, trigger_id) -> {"since": datetime|None, "fired": bool}
        self._trigger_state = {}

    def _single_condition_met(self, condition, doc):
        value = doc.get(condition["field"])
        if value is None:
            return False
        if condition["type"] == "bool":
            return bool(value) == bool(condition.get("equals", True))
        try:
            value = float(value)
        except (TypeError, ValueError):
            return False
        cmp = _COMPARATORS.get(condition.get("comparator"))
        if cmp is None:
            return False
        return cmp(value, float(condition.get("threshold", 0)))

    def _condition_met(self, trigger, doc):
        conditions = trigger.get("conditions") or []
        return bool(conditions) and all(self._single_condition_met(c, doc) for c in conditions)

    def evaluate(self, doc):
        if not doc:
            return
        now = plant_now()
        rules = list(self._db.alert_rules.find({"active": True}))

        live_keys = set()
        for rule in rules:
            if not rule.get("webhook_url"):
                continue  # malformed/pre-migration document - nothing to send to
            rule_id = rule["_id"]
            rule_consumed = False
            for trigger in rule.get("triggers", []):
                if rule_consumed:
                    break
                if not trigger.get("active", True):
                    continue
                key = (rule_id, trigger["id"])
                live_keys.add(key)
                state = self._trigger_state.setdefault(key, {"since": None, "fired": False})

                if not self._condition_met(trigger, doc):
                    state["since"] = None
                    state["fired"] = False
                    continue

                if state["since"] is None:
                    state["since"] = now
                held_s = (now - state["since"]).total_seconds()
                sustained_s = trigger.get("sustained_s") or 0
                if held_s >= sustained_s and not state["fired"]:
                    state["fired"] = True
                    self._fire(rule, trigger, doc)
                    if rule.get("repeat") == "one_time":
                        self._db.alert_rules.delete_one({"_id": rule_id})
                        rule_consumed = True

        # Forget any trigger that's since been deleted/edited away (or
        # whose rule just got consumed above), so a long-running process
        # doesn't leak memory across rule edits.
        for key in set(self._trigger_state) - live_keys:
            del self._trigger_state[key]

    def _fire(self, rule, trigger, doc):
        desc = describe_trigger(trigger)
        values = ", ".join(f"{c['field']}={doc.get(c['field'])}" for c in trigger.get("conditions", []))
        title = rule.get("label") or "Paducah Press Alert"
        message = f"{desc}\n{values}"
        if rule.get("repeat") == "one_time":
            message += "\n(one-time alert - this rule is now retired)"
        print(f"[alerts] firing rule {rule['_id']} / trigger {trigger['id']}: {desc} ({values})")
        _send_teams_async(rule["webhook_url"], title, message, recipient_email=rule.get("recipient_email"))


def run_alert_loop():
    db = get_db()
    evaluator = AlertEvaluator(db)
    print(f"[alerts] polling press_data for alert rules every {POLL_INTERVAL_S}s")
    while True:
        try:
            doc = db.press_data.find_one({}, sort=[(FLD_DATETIME, -1)])
            evaluator.evaluate(doc)
        except Exception as exc:
            print(f"[alerts] poll error (will retry): {exc}")
        time.sleep(POLL_INTERVAL_S)


def start_background_alert_poller():
    threading.Thread(target=run_alert_loop, daemon=True, name="alert-evaluator").start()
